### PR TITLE
Fix security vulnerabilities

### LINKED ISSUE #16: Fix security vulnerabilities
We have [several high or critical security vulnerabilities](https://github.com/unmock/loas3/network/alerts) within this repo. It would be great to update these packages and keep our product safe and secure.

These vulnerabilities can be tackled all at once in a single PR or broken up into multiple, it's up to you. The most important thing is that all of the tests pass and the product continues to work as expected.

### PR DESCRIPTION
**Pull request by carolstran**
Closes #16

### CODE REVIEW

**Comment by carolstran** [comment]
I've been doing it that way for no other reason besides that's how I learned to fix vulnerabilities that are in the yarn-lock file but not a direct dependency within the project.

Regarding your question, I'm a little confused. Do you mean using [`yarn upgrade`](https://yarnpkg.com/en/docs/cli/upgrade) to bump up the package version? 

Slightly related, but have you ever used the [`yarn audit`](https://yarnpkg.com/lang/en/docs/cli/audit/) function?

**Comment by carolstran** [comment]
FYI I'm going to keep this PR open as long as this conversation is ongoing because I don't want it to get lost 😇

**Comment by ksaaskil** [comment]
I haven't used `yarn audit`, sounds useful! I guess that's similar to `npm audit`? 

My approach to fixing vulnerabilities has been to basically upgrade everything, for example by deleting the lock file and regenerating it. It's not the most sophisticated and does not work for established repos with a lots of users, but for repos like ours I think "move fast and break things" is fine 😇 Also I think it's the tests' responsibility to ensure upgrading does not break anything. And if something does break without the tests showing it, I think that's a sign the package needs more tests 🙂 

But I'm definitely not against adding `resolutions`, that's completely fine!

**Comment by carolstran** [comment]
Ahhhhh excellent points, I've never approached vulnerabilities that way but you're right in that it seems like it would fit our use case nicely. I'll merge this PR for now since it's already done - but I've made a note and for next vulnerability fix I'll try that way out! Also I agree with your thoughts on the tests 💯

**Pull request merged**
